databases:
  - name: chikitsaone_production_db
    databaseName: chikitsaone
    user: chikitsaone

services:
  - type: web
    name: chikitsaone
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chikitsaone_production_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
